[package]
name = "ci-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgi = "0.6"
git2 = "0.14"
querystring = "1.1.0"
dirs = "4.0.0"
